include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_print: false
    overridden_fields: false
    prefer_initializing_formals: false
    avoid_escaping_inner_quotes: false
    avoid_classes_with_only_static_members: false
    always_use_package_imports: false


analyzer:
  errors:
    missing_required_param: error